### ISSUE TITLE
调用结果返回'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by isinry** [wlhtea/Suno2openai#10]
<img width="1075" alt="image" src="https://github.com/wlhtea/Suno2openai/assets/27894034/83047c28-5aa2-4cf6-894a-6654f40ac37e">
<img width="945" alt="image" src="https://github.com/wlhtea/Suno2openai/assets/27894034/1bc79303-6c1c-41dc-9956-306ba13bc3ef">

控制台返回None

**Comment by wlhtea** [comment]
请问有填写cookie到数据库吗？
数据库字段参考：https://github.com/wlhtea/Suno2openai?tab=readme-ov-file#-docker%E9%83%A8%E7%BD%B2
![image](https://github.com/wlhtea/Suno2openai/assets/115779315/1fff340c-ad24-460e-bb2c-7504f9c02f9b)

**Comment by isinry** [comment]
<img width="662" alt="image" src="https://github.com/wlhtea/Suno2openai/assets/27894034/dd22cd28-d708-4a46-bf65-6098dfc8479b">
<img width="692" alt="image" src="https://github.com/wlhtea/Suno2openai/assets/27894034/15f64e69-1fc6-42bc-a99d-22af8651bde5">
加上了，貌似报错更多了

**Comment by wlhtea** [comment]
这个在查着 跑起来就好哈哈哈 我晚些解决这个问题

**Comment by isinry** [comment]
😭 能不能把堆栈打印出来，目前跑起来，但是没法用

**Comment by wlhtea** [comment]
i try try 估计得明天了 my baby

**Comment by banxian007** [comment]
NoneType' object has no attribute 'items  所以到底应该怎么改，去哪里改

**Comment by banxian007** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/145275873/5604d1d5-028a-4dce-9ed2-b5ed24360ac1)
解决了吗  大家

**Comment by banxian007** [comment]
这句话啥意思，添加到数据库？
![image](https://github.com/wlhtea/Suno2openai/assets/145275873/60e478a4-4b6d-4933-ac0c-4d0caa9a225e)
我compose部署，已经把key放到update里面了
![image](https://github.com/wlhtea/Suno2openai/assets/145275873/a24d8190-b262-4253-bf0d-fb48250795a6)
还需要去添加吗，要的话 怎么弄好，我看到数据库只能上传文件，什么格式呢，把你的内容放到文件里，然后上传吗。有详细点的教程吗

**Comment by banxian007** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/145275873/3e882dd1-fd6d-4091-9ece-78e11a47b542)
没用过 ，什么情况

**Comment by banxian007** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/145275873/f32f9b57-cd38-4863-9e21-61c67a68de7d)

**Comment by banxian007** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/145275873/5c234118-51f6-43c3-8f05-635415071ebb)

**Comment by eddsi** [comment]
@banxian007 working为0表示工作
