### ISSUE TITLE
new-api

### ISSUE THREAD

**Issue by dcln78** [wlhtea/Suno2openai#12]
大佬，现在可以兼容new-api了吗？

**Comment by wlhtea** [comment]
还没喔 正在进行最近有些忙

**Comment by wlhtea** [comment]
我必须跟你宣布这个好消息 可以了 等我上传代码！！！！

**Comment by dcln78** [comment]
> 我必须跟你宣布这个好消息 可以了 等我上传代码！！！！

作者太棒了，已经用上，期待后期接入cow项目
