### ISSUE TITLE
failed to solve: process "/bin/sh -c python update_cookie_to_sql.py" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by qq137321** [wlhtea/Suno2openai#14]
使用 docker compose build && docker compose up
出现下面错误
failed to solve: process "/bin/sh -c python update_cookie_to_sql.py" did not complete successfully: exit code: 1

这是什么问题呀？是不是cookie已经存在在数据库的时候它就会这样？

**Comment by wlhtea** [comment]
这是结果 请你提供一下上面的报错部分 并且可能这个错误应该是老版本的问题，你试试拉取最新的代码

**Comment by wlhtea** [comment]
如果没什么问题 我就关闭这个issue了
