### ISSUE TITLE
程序占用CPU一直居高不下

### ISSUE THREAD

**Issue by isinry** [wlhtea/Suno2openai#15]
<img width="311" alt="image" src="https://github.com/wlhtea/Suno2openai/assets/27894034/4c664817-8b05-46c1-ada4-24165f650d02">

不知道是什么原因导致的一直占用25%的cpu，目前装了二十来个docker程序，只有作者这个是一直维持这个资源占用量

**Comment by wlhtea** [comment]
啊这 技术不太稳 我后续有空我改良一下
