### ISSUE TITLE
one-api 测试报错 ，chat-on-nextweb不知道怎么接

### ISSUE THREAD

**Issue by banxian007** [wlhtea/Suno2openai#17]

**Comment by banxian007** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/145275873/2ba50a99-73d4-49c6-bffe-59ccd1afdfca)
换cheng成这个也不行

**Comment by banxian007** [comment]
端口都放行了  sql_ip 没加http也不行 不知道什么原因了

**Comment by wlhtea** [comment]
chat-on-nextweb提供一个链接，测试报错 但是是可以正常使用的
