### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Clint-chan** [wlhtea/Suno2openai#19]

**Comment by Clint-chan** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/62379027/f42ebcda-fda7-468a-aa0a-4a04cf1721c3)

**Comment by Clint-chan** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/62379027/8d44c18d-3c1f-429b-9434-1679a98fcc79)
没法用，将working=0后，运行一遍，又变成1了

**Comment by wlhtea** [comment]
可以看看你的数据库字段吗？还有cookie请用最新的试试 看着可能是数据库的问题噢
