### ISSUE TITLE
支持arm64吗

### ISSUE THREAD

**Issue by 1152588263** [wlhtea/Suno2openai#21]

**Comment by wlhtea** [comment]
支持的

**Comment by 1152588263** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/136249763/ad1164fc-df30-451b-9a23-7c4de6fb5a1e)
好像没有arm的版本

**Comment by wlhtea** [comment]
你好 可以git clone一下 然后到需要的环境进行docker build
