### ISSUE TITLE
使用docker compose部署后update_cookie_to_sql填写完毕后无法使用

### ISSUE THREAD

**Issue by 2091280637** [wlhtea/Suno2openai#22]
![image](https://github.com/wlhtea/Suno2openai/assets/141393359/d9e7e97a-bdb3-40cb-b44e-46524796f3bc)
![image](https://github.com/wlhtea/Suno2openai/assets/141393359/8ad90914-e55b-4e06-9c58-b388a8717065)
data: {"id": "chatcmpl-Hu6Qsk7UD6OGfdHgyhjHmdvLQEVLP", "object": "chat.completion.chunk", "model": "suno-v3", "created": 1716533030, "choices": [{"index": 0, "delta": {"content": "'NoneType' object has no attribute 'items'"}, "finish_reason": null}]}

data: [DONE]

**Comment by wlhtea** [comment]
`update_cookie_to_sql` 运行结果是什么呢？

**Comment by 2091280637** [comment]
运行后没有返回结果

**Comment by wlhtea** [comment]
会不会你的sql环境填写错了 你在检查一下 或者本地远程连数据库 用pycharm跑看看 因为错误是会返回错误结果的 成功的话也会成功填入数据库

**Comment by wlhtea** [comment]
更新了一版可以clone最新的一版的`update_cookie_to_sql.py`并配置运行

**Comment by dqzboy** [comment]
pymysql.err.OperationalError: (1130, "Host 'chatgpt' is not allowed to connect to this MySQL server")

主机chatgpt是写死的吗？

**Comment by wlhtea** [comment]
默认sqlname和username 是一样的

**Comment by dqzboy** [comment]
好的，我说死活执行不了呢

**Comment by dqzboy** [comment]
Traceback (most recent call last):
  File "/data/Suno2openai/update_cookie_to_sql.py", line 35, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/data/Suno2openai/update_cookie_to_sql.py", line 32, in main
    await asyncio.gather(*tasks)
  File "/data/Suno2openai/update_cookie_to_sql.py", line 15, in fetch_limit_left
    song_gen = SongsGen(cookie)
  File "/data/Suno2openai/suno/suno.py", line 65, in __init__
    auth_token = self._get_auth_token()
  File "/data/Suno2openai/suno/suno.py", line 83, in _get_auth_token
    raise Exception("Failed to get session id")
Exception: Failed to get session id
Exception ignored in: <function Connection.__del__ at 0x7fbc1d708ca0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 1131, in __del__
  File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 339, in close
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 700, in close
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 746, in call_soon
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

session id需要管还是不用管呢？执行报错,env 如下，大佬帮忙看下问题
```shell
cat .env
BASE_URL=https://studio-api.suno.ai
SESSION_ID=cookie
SQL_name=suno
```

**Comment by wlhtea** [comment]
你的cookie有问题
![image](https://github.com/wlhtea/Suno2openai/assets/115779315/473b2aba-58b1-4625-95df-f329a6d3104e)

**Comment by dqzboy** [comment]
![image](https://github.com/wlhtea/Suno2openai/assets/42825450/fcfe6adf-65f5-4212-a0bf-715252720769)
这个是我的cookie 从suno直接复制的

**Comment by dqzboy** [comment]
> 你的cookie有问题 ![image](https://private-user-images.githubusercontent.com/115779315/336732065-473b2aba-58b1-4625-95df-f329a6d3104e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzI5NDEsIm5iZiI6MTcxNzU3MjY0MSwicGF0aCI6Ii8xMTU3NzkzMTUvMzM2NzMyMDY1LTQ3M2IyYWJhLTU4YjEtNDYyNS05NWRmLWYzMjlhNmQzMTA0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNzMwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWFlNTUwNWZkZWEzNWE4OWQxYjdhOTliNDA4ZTczNjA3MjVhNGRhMGM4OWRmZDhkOWY1MDgxZWI4NzlmMjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U1l-R6eeaUz6nrsacA5MfC1EjwLnBrDU0UiFdcg33E0)
可以了，之前获取的cookies是没登入账号的 登入账号获取的可以了

**Comment by wlhtea** [comment]
那应该就是cookie刷新了没有保活
