### ISSUE TITLE
【BUG】目前好像requirement.txt所使用的库没有给完，导致打包之后运行出现异常

### ISSUE THREAD

**Issue by Yanyutin753** [wlhtea/Suno2openai#26]
<img width="562" alt="ab30bff702eb7ab7e60d1d50290b5dd" src="https://github.com/wlhtea/Suno2openai/assets/132346501/64673d17-70c8-428c-8214-5fddc15bbb6f">

**Comment by wlhtea** [comment]
更新了 重启这个项目搞了个新的环境
