### ISSUE TITLE
这是啥情况

### ISSUE THREAD

**Issue by 666xjs** [wlhtea/Suno2openai#27]
data: {"id": "chatcmpl-n1hJzGaaRiriotGLOvAu5uTq0KZit", "object": "chat.completion.chunk", "model": "suno-v3", "created": 1717728419, "choices": [{"index": 0, "delta": {"content": "'NoneType' object has no attribute 'items'"}, "finish_reason": null}]}

data: [DONE]

**Comment by wlhtea** [comment]
数据库问题
