### ISSUE TITLE
有几率会出现卡死的情况

### ISSUE THREAD

**Issue by Yanyutin753** [wlhtea/Suno2openai#28]
不知道是不是初始化sql的那块有点问题，有时候会出现卡死的情况，发很多请求，服务端日志也不会显示

**Comment by Yanyutin753** [comment]
我自己把cookie的选择改为随机选取，然后把creat_pool那个函数修改了一下，观察一下，还会不会出现这个情况

**Comment by wlhtea** [comment]
十分感谢！！！ 我会拉取下来再看看 然后再合并但是可能得明天了 这几天比较忙

**Comment by Yanyutin753** [comment]
可以的 我后面还补一个刷新cookie

**Comment by Yanyutin753** [comment]
之前添加会增加次数，这个bug我在这次pr修了一下

**Comment by Yanyutin753** [comment]
> 十分感谢！！！ 我会拉取下来再看看 然后再合并但是可能得明天了 这几天比较忙
> 
> 问题的原因可能是第一个cookie还没完成歌曲生成就又调用它了 所以根本的解决方法我觉得应该检测是cdn的链接生成了（cdn链接就是需要等待两分钟才可以打开的那个链接） 再结束响应同时修改数据库working为0，及工作结束

还真可能是这个原因，可以的，我再修修我的pr

**Comment by wlhtea** [comment]
> 还真可能是这个原因，可以的，今天我再修修我的PR

感谢！我尽早看看前面的那些commit，这个其实main中 有一个判断

```python
                else:
                    content_wait = "."
                    yield f"""data:""" + ' ' + f"""{json.dumps({"id": f"chatcmpl-{chat_id}", "object": "chat.completion.chunk", "model": "suno-v3", "created": timeStamp, "choices": [{"index": 0, "delta": {"content": content_wait}, "finish_reason": None}]})}\n\n"""
                    print(attempts)
                    print(now_data)
                    time.sleep(5)  # 等待5秒再次尝试
                    attempts += 1
```
就是为这个铺垫。只是一直有点懒没有去研究cdn链接的获取哈哈 后面发现歌曲id拼一下就行了 就直接拼出来返回算了。

**Comment by Yanyutin753** [comment]
不过我现在基本上感受不到了，也不知道是不是这个原因，我现在用的随机选取的，堆了30个号，用来做小组作业的测试，其他估计问题不大

**Comment by Yanyutin753** [comment]
更了一下自动刷新，然后开了个接口，感觉可以为后面搞个前端管理cookies，埋个铺垫，就是没时间弄🥹

**Comment by Yanyutin753** [comment]
> 十分感谢！！！ 我会拉取下来再看看 然后再合并但是可能得明天了 这几天比较忙
> 
> 问题的原因可能是第一个cookie还没完成歌曲生成就又调用它了 所以根本的解决方法我觉得应该检测是cdn的链接生成了（cdn链接就是需要等待两分钟才可以打开的那个链接） 再结束响应同时修改数据库working为0，及工作结束

如果等待一段时候在相应的话 我感觉对前端很不友好啊 我试试你说的这个错误，看看是不是这个原因

**Comment by Yanyutin753** [comment]
> > 十分感谢！！！ 我会拉取下来再看看 然后再合并但是可能得明天了 这几天比较忙
> > 
> > 问题的原因可能是第一个cookie还没完成歌曲生成就又调用它了 所以根本的解决方法我觉得应该检测是cdn的链接生成了（cdn链接就是需要等待两分钟才可以打开的那个链接） 再结束响应同时修改数据库working为0，及工作结束
> 
> 如果等待一段时候在相应的话 我感觉对前端很不友好啊 我试试你说的这个错误，看看是不是这个原因

经过测试，我在只有一个cookies的情况下，并没有发现第一次创作完歌曲立即去提问导致卡死的情况，估计是原来数据库初始化的问题

**Comment by wlhtea** [comment]
> 经过测试，我在只有一个cookies的情况下，并发现第一次创作完歌曲立即去提问确实导致卡死的情况🥹

是的 没关系 我已经解决了这个问题 昨天一个项目重新构建了数据库结构

| 字段名称 | 数据类型          | 描述                                   |
| -------- | ----------------- | -------------------------------------- |
| id       | INT               | 主键，自增                             |
| cookie   | TEXT              | 不可为空的文本数据，存储cookie信息     |
| songID   | VARCHAR(255)      | 可变长度字符串，最大长度255，存储歌曲ID|
| songID2  | VARCHAR(255)      | 可变长度字符串，最大长度255，存储歌曲ID|
| count    | INT               | 整数类型，存储计数                    |
| time     | TIMESTAMP         | 时间戳类型，默认当前时间              |

① 首先调用cookie生成音乐时（cookie选择条件为：`count>0`和`songid`和`songid2`都为空） 会把两个歌曲id记录 
② 获取生成的歌曲信息会传入歌曲id索引得到对应的cookie 再去请求生成的歌曲信息（当然用其他的cookie也可以 只是为了让其他cookie不要相互冲突均衡使用）
③ 因为请求歌曲到结束会出现字样 `"status":"complete"`，如果没有结束是`"status":"streaming"` 进行判断 如果出现了就删除数据库中歌曲id信息，表明该cookie处于空闲状态。
当然里面有些风险需要规避，比如可能异步的时候有其他的请求再删除歌曲id后依旧去请求的 可能就获取不到cookie信息 这个时候就需要用到`①`中的cookie获取规则获取一个cookie即可。

这次完成的工作：
① 歌曲生成的cookie选择避免冲突。
② 歌曲续写。
③ 数据库重构。
④ 歌曲url的生成而不再是拼接。
⑤ cookie更新写入bug修复。

**Comment by Yanyutin753** [comment]
time 哈哈哈 我昨天也想到这个了

**Comment by Yanyutin753** [comment]
其实最简单的方法可以在你拿到cookie的时候判断一下当前的时间戳和cookie对应的上一次提问的时间戳比较，看是否过了一段时间，这样其实就可以了

#### 唯一的担心
修改之后，输出的速度会不会变慢，因为很多时候，我们还是比较看速度的，比如我用到机器人去做试验的话，就是得先要速度，能最快收到完整的消息，就更好了

**Comment by wlhtea** [comment]
如果要速度的话可能得用到redies 但是这个数据库没有使用过 我后面试试 的确速度会慢 但是应该是能接受的 毕竟suno生成的歌曲也是需要等待时间的。
如你所说的这样去判断可能有点奇怪，因为这并不是真正的结束时间，并且如果在生产环境中有十几个已经正在使用的cookie，去判断也会影响到响应速度，如果是随机可能还好，但是应该不是最好的做法这样。

**Comment by Yanyutin753** [comment]
歌曲续写

对于这个点的话，我有点想法，可以做一个工作流的形式，尽大可能的发挥出suno的实力哈哈哈哈，因为我发现我们写提示词的话，单单chat，有些要求并不会让suno知道，我们可以内置一个工作流，不单单是prompt，还可以改变风格啥的

**Comment by Yanyutin753** [comment]
> 如果要速度的话可能得用到redies 但是这个数据库没有使用过 我后面试试 的确速度会慢 但是应该是能接受的 毕竟suno生成的歌曲也是需要等待时间的。 如你所说的这样去判断可能有点奇怪，因为这并不是真正的结束时间，并且如果在生产环境中有十几个已经正在使用的cookie，去判断也会影响到响应速度，如果是随机可能还好，但是应该不是最好的做法这样。

不是的，这个速度应该很快的，相当于我先找到count大于0且不在working的cookie，然后在里面挑选一个时间戳距离现在大于几分钟的cookie，这个直接用mysql查的话，应该挺快的

**Comment by Yanyutin753** [comment]
相当于我每次请求对应的cookie，都会在对应的cookie加上当前请求的时间戳，方便下次判断

**Comment by wlhtea** [comment]
天才！！ 我刚刚也在想 因为如果只是像`chat-next-web`这样的前端项目是无法发送相应的请求参数的 只能通过一些http的请求工具。那么或许下一个版本可以接入`fastgpt`或者`dify`了

**Comment by wlhtea** [comment]
> 相当于我每次请求对应的cookie，都会在对应的cookie加上当前请求的时间戳，方便下次判断

明白了 但是还有一种特殊的情况是cookie全部负载了

**Comment by Yanyutin753** [comment]
> > 相当于我每次请求对应的cookie，都会在对应的cookie加上当前请求的时间戳，方便下次判断
> 
> 明白了 但是还有一种特殊的情况是cookie全部负载了

这样的话，返回429就可以了，其实全负载这个请求，再去请求也是卡死，不如返回429

**Comment by Yanyutin753** [comment]
> > 相当于我每次请求对应的cookie，都会在对应的cookie加上当前请求的时间戳，方便下次判断
> 
> 明白了 但是还有一种特殊的情况是cookie全部负载了，生成歌曲的时间也不是固定的

还真是，但是这是最简单的改变方式哈哈哈，基本不用修改其他判断

**Comment by wlhtea** [comment]
> 天才！！ 我刚刚也在想 因为如果只是像`chat-next-web`这样的前端项目是无法发送相应的请求参数的 只能通过一些http的请求工具。那么或许下一个版本可以接入`fastgpt`或者`dify`了

噢 一个200star不到的项目有点庞大 应该能引入gpt、claude接口 自己写一个工作流就好了 不然显得过于臃肿了 脱裤子放屁的感觉哈哈

**Comment by Yanyutin753** [comment]
> > 天才！！ 我刚刚也在想 因为如果只是像`chat-next-web`这样的前端项目是无法发送相应的请求参数的 只能通过一些http的请求工具。那么或许下一个版本可以接入`fastgpt`或者`dify`了
> 
> 噢 一个200star不到的项目有点庞大 应该能引入gpt、claude接口 自己写一个工作流就好了 不然显得过于臃肿了 脱裤子放屁的感觉哈哈

哈哈哈哈哈哈哈哈哈哈，还真是，感觉大家对于suno的热情不是很高啊

**Comment by Yanyutin753** [comment]
估计是缺少账号，而且没有傻瓜式的项目，我前几天就有人吐槽不会弄这个，项目跑起来不会用😭

**Comment by Yanyutin753** [comment]
大佬，方便加个v吗🤩

**Comment by wlhtea** [comment]
> 大佬，方便加个v吗🤩

🆗的 w13622796528
