### ISSUE TITLE
大佬，项目部署遇到两个问题，麻烦解惑！

### ISSUE THREAD

**Issue by dcln78** [wlhtea/Suno2openai#37]
大佬，有两个问题，
1.这两个参数应该怎么填呢？
COOKIES_PREFIX=查询cookies的接口前缀，一定要以/开头
AUTH_KEY=cookies操作密钥

2.添加到new-api中，是选自定义渠道吗？项目地址填http://IP:8000,
密钥不用填吗？放到前端之后用不了
![01](https://github.com/wlhtea/Suno2openai/assets/26784058/9a944a2a-c482-44bf-9157-da7bd1c59849)

**Comment by wlhtea** [comment]
这块最近更新速度太快了 主要是这个佬效率太猛了 @Yanyutin753  这块内容还没在readme上加上
`AUTH_KEY`:这个是密钥 和openai格式那样传递即可
`COOKIES_PREFIX`这个是查询cookies池子的信息的 post http://127.0.0.1:8000/{COOKIES_PREFIX}/cookies

**Comment by dcln78** [comment]
好的

> 这块最近更新速度太快了 主要是这个佬效率太猛了 @Yanyutin753 这块内容还没在readme上加上 `AUTH_KEY`:这个是密钥 和openai格式那样传递即可 `COOKIES_PREFIX`这个是查询cookies池子的信息的 post [http://127.0.0.1:8000/{COOKIES_PREFIX}/cookies](http://127.0.0.1:8000/%7BCOOKIES_PREFIX%7D/cookies)

好的 谢谢大佬解答，等有时间了补上吧，部署过程中还是有点小坑的

**Comment by wlhtea** [comment]
的确的确 好的会的
