### ISSUE TITLE
新版本cookie没有地方填写了吗？

### ISSUE THREAD

**Issue by dcln78** [wlhtea/Suno2openai#47]

**Comment by Yanyutin753** [comment]
不用填写 现在直接请求

**Comment by dcln78** [comment]
> 不用填写 现在直接请求

那现在是不用账号也可以使用了？

**Comment by Yanyutin753** [comment]
不是 你要用请求填写cookies

**Comment by dcln78** [comment]
> 不是 你要用请求填写cookies

那感觉还是之前的版本添加比较方便吧

**Comment by dcln78** [comment]
> 不是 你要用请求填写cookies

COOKIES_PREFIX: 'http://127.0.0.1:8000/{COOKIES_PREFIX}/cookies'  这个参数就这么填吗?

**Comment by AuYuHui** [comment]
现在都不用保活了？

**Comment by Yanyutin753** [comment]
定时保 但是最大还是只有7天

**Comment by Yanyutin753** [comment]
定时保 但是最大还是只有7天

**Comment by turndown** [comment]
> 不用填写 现在直接请求

你好，请问下是用put请求增加cookie吗，通过web页面添加cookie现在是取消掉了是吗？
另外我这边通过put请求增加cookie一直说成功率0，是什么问题啊？
![image](https://github.com/user-attachments/assets/72a5a98c-bf57-4060-ad7b-fa03167ba495)
![image](https://github.com/user-attachments/assets/182ea250-1532-4a77-b2ba-5e39942c0e16)
