### ISSUE TITLE
大佬，mysql的库名能自定义吗？

### ISSUE THREAD

**Issue by itq5** [wlhtea/Suno2openai#5]
大佬，mysql的库名能自定义吗？

**Comment by wlhtea** [comment]
当然可以 init_sql.. 和update_sql... 两个代码修改即可

**Comment by itq5** [comment]
docker运行时，.env文件缺失

**Comment by wlhtea** [comment]
抱歉 上传的时候忘了改env名字 被GitHub隐藏了 需要创建一个.env文件，内容如下：
BASE_URL=https://studio-api.suno.ai
SESSION_ID=cookie
不用修改内容

**Comment by wangasa** [comment]
用1panel部署docker  mysql对接不上，init_sql.py没有反应。

**Comment by wlhtea** [comment]
你好已经重新更新了代码，请麻烦重新拉取和部署！！

**Comment by wangasa** [comment]
> 你好已经重新更新了代码，请麻烦重新拉取和部署！！

@wlhtea  1panel还是连接不上数据库...大佬你用1panel搭一个看看？https://github.com/1Panel-dev/1Panel
我按用宝塔能正常搭建出来

**Comment by wlhtea** [comment]
是的 用宝塔比较直观 1panel没试过噢

**Comment by wangasa** [comment]
@wlhtea 试试1panel，go语言速度非常快，还带自动续签，全是容器化管理极其方便。

**Comment by wlhtea** [comment]
好的 我留着这个issue 现在在看new-api源码 等解决了这个问题 我再来试试！
