### ISSUE TITLE
使用lobebhub调用报错

### ISSUE THREAD

**Issue by itq5** [wlhtea/Suno2openai#6]
![image](https://github.com/wlhtea/Suno2openai/assets/42521985/041d65d5-49dc-4920-bbfa-8a407f413393)

![image](https://github.com/wlhtea/Suno2openai/assets/42521985/40a5e574-7e4e-4691-9241-2368708c033a)

**Comment by wlhtea** [comment]
已经更新，看看是不是cookie不行了，现在免费的cookie应该是调用不了的
