### ISSUE TITLE
OneAPI调用报错

### ISSUE THREAD

**Issue by KarlLee830** [wlhtea/Suno2openai#7]
报错内容：
`错误：invalid character 'd' looking for beginning of value`

日志内容
`500 Internal Server Error {"error":{"code":"decode_response_failed","message":"invalid character 'd' looking for beginning of value (request id: 202404062244052291329202Svobm0S)","type":"one_api_error"}}`

直接使用chatbox本地调用api
虽可生成内容，但生成完毕后仍然会带报错信息
```
未知错误。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

Unexpected token ''', "['DONE']" is not valid JSON
```

![image](https://github.com/wlhtea/Suno2openai/assets/61072264/f0650938-a99d-4f66-8c24-be902ea1357c)

**Comment by wlhtea** [comment]
这个我知道 后续跟新好了 在这里dd你

**Comment by wlhtea** [comment]
你好，请再试试看还会报错吗？

**Comment by KarlLee830** [comment]
我看了下代码，貌似数据库名和用户名是保持一致的吗，这个最好还是拆开比较好🤔

**Comment by KarlLee830** [comment]
> 你好，请再试试看还会报错吗？

wlhtea/suno2openai:0.1.0 尝试了一下这个镜像，仍然报错`invalid character 'd' looking for beginning of value`

**Comment by wlhtea** [comment]
这是环境没有配置好的问题
docker按照[要求进行配置](https://github.com/wlhtea/Suno2openai#-docker-deployment)
docker 需要[配置env文件](https://github.com/wlhtea/Suno2openai#-docker-compose-deployment)

**Comment by KarlLee830** [comment]
> 这是环境没有配置好的问题 docker按照[要求进行配置](https://github.com/wlhtea/Suno2openai#-docker-deployment) docker 需要[配置env文件](https://github.com/wlhtea/Suno2openai#-docker-compose-deployment)

我的环境变量应该是没问题的
我自己debug后尝试手动将数据库内的working一栏数值重新修改为0后
再尝试调用接口，working数值被重新修改为1，可以正常返回内容了
![image](https://github.com/wlhtea/Suno2openai/assets/61072264/51ae36bc-12cf-4112-80ca-21e3178ac44e)

**Comment by wlhtea** [comment]
是的 可能是您用的是之前的代码有些bug 对你照成不方便 抱歉
