### ISSUE TITLE
调用次数\输出不完整

### ISSUE THREAD

**Issue by Passerby1011** [wlhtea/Suno2openai#9]
正常来说每个账户每天可以调用5次，但是我只请求了两次，那个cookie就不能用了，数据库里的working变成了1，调用次数count还有3次，想问一下这个调用次数每天会自己刷新吗?
同时还有输出不完整的问题如图：歌曲链接没有输出出来
![image](https://github.com/wlhtea/Suno2openai/assets/63802758/a42cce91-2083-4e5c-95b9-3b40c1f49ef3)

**Comment by wlhtea** [comment]
这个应该是出错了 然后最后没有更改working状态 我修改一下代码
